// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"DF_BattleMenuCommandList","status":true,"description":"DF通用脚本 - 菜单屏蔽","parameters":{"isAttackDisable":"Disable","isDefendDisable":"Disable","isSkillsDisable":"","isItemsDisable":"Disable"}},
{"name":"DF_ParallelEquipmentSlot","status":true,"description":"DF通用脚本 - 平行装备槽","parameters":{}}
];
